<?php
    $testing_request = '{
        "type": "message_new",
        "object": {
            "id": 32,
            "date": 1614415943,
            "out": 0,
            "user_id": 381375372,
            "read_state": 0,
            "title": "",
            "body": "",
            "owner_ids": [],
            "fwd_messages": [
                {
                    "user_id": 381375372,
                    "date": 1613983826,
                    "body": "",
                    "owner_ids": [],
                    "fwd_messages": [
                        {
                            "user_id": 381375372,
                            "date": 1613974384,
                            "body": "",
                            "owner_ids": [],
                            "fwd_messages": [
                                {
                                    "user_id": 381375372,
                                    "date": 1613918814,
                                    "body": "",
                                    "attachments": [
                                        {
                                            "type": "doc",
                                            "doc": {
                                                "id": 589515504,
                                                "owner_id": 381375372,
                                                "title": "381375372_1613918812.ogg",
                                                "size": 13171,
                                                "ext": "ogg",
                                                "date": 1613918814,
                                                "type": 5,
                                                "url": "https://vk.com/doc381375372_589515504?hash=cf35397dc0ccba20a1&dl=GM4DCMZXGUZTOMQ:1614415943:51ed8c2d22a9673388&api=1&no_preview=1",
                                                "preview": {
                                                    "audio_msg": {
                                                        "duration": 5,
                                                        "link_mp3": "https://psv4.userapi.com/c524032//u381375372/audiomsg/d47/2f28d76cec.mp3",
                                                        "link_ogg": "https://psv4.userapi.com/c524032//u381375372/audiomsg/d47/2f28d76cec.ogg",
                                                        "waveform": [
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            2,
                                                            6,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            2,
                                                            3,
                                                            2,
                                                            1,
                                                            1,
                                                            3,
                                                            5,
                                                            0,
                                                            2,
                                                            4,
                                                            2,
                                                            0,
                                                            2,
                                                            1,
                                                            1,
                                                            3,
                                                            2,
                                                            0,
                                                            5,
                                                            3,
                                                            2,
                                                            2,
                                                            3,
                                                            5,
                                                            3,
                                                            7,
                                                            2,
                                                            1,
                                                            0,
                                                            0,
                                                            0,
                                                            5,
                                                            21,
                                                            11,
                                                            1,
                                                            3,
                                                            4,
                                                            2,
                                                            0,
                                                            0,
                                                            1,
                                                            2,
                                                            0,
                                                            3,
                                                            6,
                                                            0,
                                                            2,
                                                            2,
                                                            0,
                                                            0,
                                                            3,
                                                            1,
                                                            3,
                                                            1,
                                                            1,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            0,
                                                            2,
                                                            3,
                                                            1,
                                                            0,
                                                            0,
                                                            0,
                                                            4,
                                                            1,
                                                            4,
                                                            3,
                                                            4,
                                                            2,
                                                            6,
                                                            12,
                                                            8,
                                                            0,
                                                            1,
                                                            2,
                                                            3,
                                                            1,
                                                            3,
                                                            0,
                                                            0,
                                                            19,
                                                            23,
                                                            1,
                                                            0,
                                                            0,
                                                            1,
                                                            0,
                                                            1,
                                                            0,
                                                            3,
                                                            0,
                                                            9,
                                                            5,
                                                            0,
                                                            31,
                                                            28,
                                                            4,
                                                            14,
                                                            5,
                                                            0,
                                                            0,
                                                            0,
                                                            1
                                                        ]
                                                    }
                                                },
                                                "access_key": "ab1b95b4950c78a689"
                                            }
                                        }
                                    ],
                                    "owner_ids": []
                                },
                                {
                                    "user_id": 381375372,
                                    "date": 1613974372,
                                    "body": "",
                                    "owner_ids": [],
                                    "fwd_messages": [
                                        {
                                            "user_id": 381375372,
                                            "date": 1613974350,
                                            "body": "",
                                            "owner_ids": [],
                                            "fwd_messages": [
                                                {
                                                    "user_id": 381375372,
                                                    "date": 1613750680,
                                                    "body": "",
                                                    "attachments": [
                                                        {
                                                            "type": "doc",
                                                            "doc": {
                                                                "id": 589294467,
                                                                "owner_id": 381375372,
                                                                "title": "381375372_1613750676.ogg",
                                                                "size": 25688,
                                                                "ext": "ogg",
                                                                "date": 1613750679,
                                                                "type": 5,
                                                                "url": "https://vk.com/doc381375372_589294467?hash=ca2d37647c0c116b54&dl=GM4DCMZXGUZTOMQ:1614415943:ce346942082ab43bc9&api=1&no_preview=1",
                                                                "preview": {
                                                                    "audio_msg": {
                                                                        "duration": 10,
                                                                        "link_mp3": "https://psv4.userapi.com/c618331//u381375372/audiomsg/d1/295fb19ea3.mp3",
                                                                        "link_ogg": "https://psv4.userapi.com/c618331//u381375372/audiomsg/d1/295fb19ea3.ogg",
                                                                        "waveform": [
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            2,
                                                                            1,
                                                                            1,
                                                                            1,
                                                                            0,
                                                                            6,
                                                                            16,
                                                                            8,
                                                                            13,
                                                                            2,
                                                                            0,
                                                                            9,
                                                                            7,
                                                                            0,
                                                                            2,
                                                                            2,
                                                                            2,
                                                                            4,
                                                                            2,
                                                                            22,
                                                                            1,
                                                                            4,
                                                                            6,
                                                                            1,
                                                                            1,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            5,
                                                                            2,
                                                                            0,
                                                                            0,
                                                                            2,
                                                                            0,
                                                                            4,
                                                                            0,
                                                                            4,
                                                                            0,
                                                                            0,
                                                                            1,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            2,
                                                                            0,
                                                                            1,
                                                                            0,
                                                                            1,
                                                                            0,
                                                                            5,
                                                                            0,
                                                                            2,
                                                                            0,
                                                                            2,
                                                                            1,
                                                                            1,
                                                                            8,
                                                                            1,
                                                                            3,
                                                                            6,
                                                                            0,
                                                                            1,
                                                                            4,
                                                                            8,
                                                                            0,
                                                                            3,
                                                                            3,
                                                                            0,
                                                                            1,
                                                                            6,
                                                                            4,
                                                                            8,
                                                                            9,
                                                                            1,
                                                                            0,
                                                                            0,
                                                                            1,
                                                                            1,
                                                                            1,
                                                                            2,
                                                                            5,
                                                                            2,
                                                                            2,
                                                                            2,
                                                                            0,
                                                                            1,
                                                                            8,
                                                                            31,
                                                                            8,
                                                                            0,
                                                                            2,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0
                                                                        ]
                                                                    }
                                                                },
                                                                "access_key": "54ba8b64c000653443"
                                                            }
                                                        }
                                                    ],
                                                    "owner_ids": []
                                                },
                                                {
                                                    "user_id": 381375372,
                                                    "date": 1613829673,
                                                    "body": "",
                                                    "attachments": [
                                                        {
                                                            "type": "doc",
                                                            "doc": {
                                                                "id": 589398285,
                                                                "owner_id": 381375372,
                                                                "title": "381375372_1613829187.ogg",
                                                                "size": 92378,
                                                                "ext": "ogg",
                                                                "date": 1613829672,
                                                                "type": 5,
                                                                "url": "https://vk.com/doc381375372_589398285?hash=2528bd1dac906b7c01&dl=GM4DCMZXGUZTOMQ:1614415943:1e0e778c45f646a53c&api=1&no_preview=1",
                                                                "preview": {
                                                                    "audio_msg": {
                                                                        "duration": 36,
                                                                        "link_mp3": "https://psv4.userapi.com/c533336//u381375372/audiomsg/d19/fee33f9f1d.mp3",
                                                                        "link_ogg": "https://psv4.userapi.com/c533336//u381375372/audiomsg/d19/fee33f9f1d.ogg",
                                                                        "waveform": [
                                                                            0,
                                                                            0,
                                                                            5,
                                                                            13,
                                                                            0,
                                                                            4,
                                                                            0,
                                                                            1,
                                                                            0,
                                                                            1,
                                                                            1,
                                                                            0,
                                                                            1,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            0,
                                                                            8,
                                                                            28,
                                                                            12,
                                                                            0,
                                                                            1,
                                                                            2,
                                                                            0,
                                                                            3,
                                                                            3,
                                                                            14,
                                                                            24,
                                                                            6,
                                                                            18,
                                                                            8,
                                                                            6,
                                                                            20,
                                                                            7,
                                                                            2,
                                                                            9,
                                                                            11,
                                                                            14,
                                                                            7,
                                                                            10,
                                                                            11,
                                                                            2,
                                                                            4,
                                                                            3,
                                                                            10,
                                                                            5,
                                                                            3,
                                                                            4,
                                                                            11,
                                                                            2,
                                                                            1,
                                                                            2,
                                                                            4,
                                                                            0,
                                                                            31,
                                                                            3,
                                                                            24,
                                                                            2,
                                                                            2,
                                                                            3,
                                                                            1,
                                                                            1,
                                                                            5,
                                                                            24,
                                                                            8,
                                                                            2,
                                                                            8,
                                                                            5,
                                                                            15,
                                                                            14,
                                                                            7,
                                                                            24,
                                                                            3,
                                                                            13,
                                                                            15,
                                                                            31,
                                                                            26,
                                                                            2,
                                                                            1,
                                                                            1,
                                                                            1,
                                                                            9,
                                                                            16,
                                                                            7,
                                                                            1,
                                                                            12,
                                                                            12,
                                                                            9,
                                                                            13,
                                                                            3,
                                                                            1,
                                                                            4,
                                                                            2,
                                                                            0,
                                                                            1,
                                                                            2,
                                                                            14,
                                                                            7,
                                                                            4,
                                                                            25,
                                                                            10,
                                                                            12,
                                                                            10,
                                                                            11,
                                                                            11,
                                                                            6,
                                                                            1,
                                                                            1,
                                                                            5,
                                                                            8,
                                                                            1,
                                                                            7,
                                                                            3,
                                                                            2,
                                                                            13,
                                                                            3,
                                                                            21,
                                                                            5,
                                                                            9,
                                                                            0,
                                                                            2,
                                                                            0
                                                                        ]
                                                                    }
                                                                },
                                                                "access_key": "761a601086f2f0e9fd"
                                                            }
                                                        }
                                                    ],
                                                    "owner_ids": []
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        "group_id": 202891620,
        "event_id": "cbfa5aae43505e621a44d223b6e1b24d06897919",
        "secret": "DebugToken"
    }';
 
    //Получаем и декодируем уведомление
    $data = json_decode($testing_request);
    
    //Проверяем, что находится в поле "type"
    switch ($data->type) {
        //Если это уведомление о новом сообщении...
        case 'message_new':
            // Инициализируем колбэк создание сообщение
            include_once('objects/message.php');

            // Выполняем колбэк на создания сообщения
            onMessageCreated($data->object);
        
            //Возвращаем ok серверу Callback API
            echo 'ok';
            break;
    }    
?>